name: 'Setup SHAs'
description: 'Github action which sets the base and head SHAs required for the `nx affected` commands in CI'
inputs:
  node_version:
    description: 'Node version'
    required: false
    default: '20'

runs:
  using: 'composite'
  steps:
    - name: Derive appropriate SHAs
      id: setSHAs
      uses: nrwl/nx-set-shas@v4

    - name: Print SHAs
      shell: bash
      run: |
        echo "BASE: ${{ steps.setSHAs.outputs.base }}"
        echo "HEAD: ${{ steps.setSHAs.outputs.head }}"
