name: 'Setup Node & NPM'
description: 'GitHub action that sets the node environment for a workflow and downloads NPM dependencies.'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: 'https://registry.npmjs.org'
        # cache: npm
        # cache-dependency-path: package-lock.json

    - name: Npm Install
      run: npm ci --ignore-scripts
      shell: bash
